config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :requests, :except => [:edit, :show, :destroy]
  resources :schedules, :only => [:index, :edit, :update]
  resources :constituencies, :only => [:index, :show]
  root to: 'home#index'
  resources :users, :only => [:index, :update] do
    collection do
      get '/candidates', to: 'users#candidates'
      get '/voters', to: 'users#voters'
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

# ApplicationRecord
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/constituency.rb
# frozen_string_literal: true

class Constituency < ApplicationRecord
  has_many :users, dependent: :destroy
end

app/models/request.rb
# frozen_string_literal: true

class Request < ApplicationRecord
  has_one_attached :avatar

  validates :name, presence: true
  validates :party_name, presence: true
  validates :avatar, presence: true
  validates :cnic, presence: true, length: { is: 13 }
  validates :constituency_name, presence: true
  enum request_status: { pending: 0, approved: 1 }

  def access_credentials(current_user)
    self.name = current_user.name
    self.cnic = current_user.cnic
    self.constituency_name = current_user.constituency_name
  end

  def update_status(user)
    if user.nil?
      false
    else
      update(request_status: :approved)
      user.update(party_name: party_name, user_status: :candidate) if user.voter!
      user.update(party_name: party_name, user_status: :super_admin) if user.admin?
      attach_avatar(user)
      true
    end
  end

  def attach_avatar(user)
    user.avatar.purge
    user.avatar.attach(avatar)
    user.avatar.attach(avatar.blob_id)
    user.avatar.attach(avatar_blob)
  end
end

app/models/schedule.rb
# frozen_string_literal: true

class Schedule < ApplicationRecord
  validates :election_start_time, presence: true
  validates :election_end_time, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum user_status: { voter: 0, candidate: 1, admin: 2, super_admin: 3 }

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :cnic, presence: true, length: { is: 13 }

  has_one_attached :avatar
  has_one_attached :image
  belongs_to :constituency
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Application controller
class ApplicationController < ActionController::Base
  include Pundit::Authorization
  before_action :configure_permitted_parameters, if: :devise_controller?
  rescue_from Pundit::NotAuthorizedError do
    flash[:alert] = 'You are not authorized to do required action !'
    redirect_to root_url
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:invite,
                                      keys: %i[name cnic constituency_name email user_status constituency_id])
    devise_parameter_sanitizer.permit(:accept_invitation, keys: [:image])
  end
end

app/controllers/constituencies_controller.rb
# frozen_string_literal: true

# ConstituenciesController
class ConstituenciesController < ApplicationController
  before_action :find_constituency, only: %i[show]
  def index
    @constituencies = Constituency.all
    authorize @constituencies
  end

  def show
    @userlists = @constituency.users.where(user_status: %i[candidate super_admin])
  end

  private

  def find_constituency
    @constituency = Constituency.find_by(id: params[:id])
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# HomeController
class HomeController < ApplicationController
  def index; end
end

app/controllers/requests_controller.rb
# frozen_string_literal: true

# RequestsController
class RequestsController < ApplicationController
  before_action :find_request, only: %i[update]
  before_action :find_requesting_user, only: %i[update]
  def index
    @requests = Request.all
    authorize @requests
  end

  def new
    @request = Request.new
    authorize @request
  end

  def create
    @request = Request.new(request_params)
    authorize @request
    @request.access_credentials(current_user)
    if @request.save
      flash[:alert] = 'Request created'
      redirect_to root_path
    else
      flash[:notice] = 'request not created'
      render 'new'
    end
  end

  def update
    if @request.update_status(@user)
      flash[:alert] = 'Request approved'
      redirect_to requests_path
    else
      flash[:notice] = 'invalid request'
    end
  end

  private

  def request_params
    params.require(:request).permit(:party_name, :avatar)
  end

  def find_request
    @request = Request.find_by(id: params[:id])
  end

  def find_requesting_user
    @user = User.find_by(cnic: @request.cnic)
  end
end

app/controllers/schedules_controller.rb
# frozen_string_literal: true

# SchedulesController
class SchedulesController < ApplicationController
  before_action :find_schedule, only: %i[update edit]
  def index
    @schedules = Schedule.all
  end

  def edit; end

  def update
    authorize @schedule
    if @schedule.update(schedule_params)
      flash[:alert] = 'Schedule edited'
      redirect_to schedules_path
    else
      flash[:alert] = 'schedule not edited'
      render 'edit'
    end
  end

  private

  def schedule_params
    params.require(:schedule).permit(:election_start_time, :election_end_time)
  end

  def find_schedule
    @schedule = Schedule.find_by(id: params[:id])
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# UsersController
class UsersController < ApplicationController
  before_action :find_user, only: %i[update]
  def index
    @userlists = User.all
    authorize @userlists
  end

  def candidates
    @userlists = Constituency.find_by(id: current_user.constituency_id).users.where(user_status: %i[candidate super_admin])
  end

  def voters
    @userlists = Constituency.find_by(id: current_user.constituency_id).users
    authorize @userlists
  end

  def update
    current_user.update(voted: true)
    flash[:alert] = 'Voted'
    redirect_to candidates_users_path
  end

  private

  def find_user
    @candidate = User.find_by(id: params[:id])
    @candidate.increment!(:total_votes_gain) # rubocop:disable Rails/SkipsModelValidations
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# ApplicationHelper
module ApplicationHelper
end

app/views/candidateslists/index.html.erb
<h1>Candidates</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>CNIC</th>
      <th>Email</th>
      <th>Constituency</th>
      <th>Total votes gain</th>
      <th>Party name</th>
      <th>Symbol</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @userlists.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.cnic %></td>
        <td><%= user.email %></td>
        <td><%= user.constituency_name %></td>
        <td><%= user.total_votes_gain %></td>
        <td><%= user.party_name%>
        <td><%= image_tag user.avatar, width: "100px" if user.avatar.attached?%>
        <td>
          <% if current_user.voted == false && DateTime.now.between?(Schedule.first.election_start_time, Schedule.first.election_end_time)%>


            <%= button_to "Vote",userlist_path(user),method: :patch%>

          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/constituencies/index.html.erb
<h1>Constituencies</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @constituencies.each do |constituency| %>
      <tr>
        <td><%= constituency.name %></td>
        <td><%= link_to 'Show', constituency %></td>
      </tr>
    <%end%>
  </tbody>


</table>

app/views/constituencies/show.html.erb
<h1>Candidates</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>CNIC</th>
      <th>Email</th>
      <th>Constituency</th>
      <th>Total votes gain</th>
      <th>Party name</th>
      <th>Symbol</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @userlists.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.cnic %></td>
        <td><%= user.email %></td>
        <td><%= user.constituency_name %></td>
        <td><%= user.total_votes_gain %></td>
        <td><%= user.party_name%></td>
        <td><%= image_tag user.avatar, width: "100px" if user.avatar.attached?%></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Voting Machine</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Home', root_path, class:"nav-link"%>
      </li>
      <% if user_signed_in? %>
        <% if DateTime.now >= Schedule.first.election_end_time%>
          <li class="nav-item">
            <%= link_to 'Dashboard', constituencies_path, class:"nav-link"%>
          </li>
        <% end %>
        <% if current_user.admin? %>
          </li class="nav-item">
            <%= link_to 'New request for candidate-ship', new_request_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'Requests', requests_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'Invite', new_user_invitation_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'Users', users_path, class:"nav-link"%>
          </li>
        <% elsif current_user.super_admin? %>
          <li class="nav-item">
            <%= link_to 'Requests', requests_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'Invite', new_user_invitation_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'Users', users_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'Voters', voters_users_path, class:"nav-link"%>
          </li>
        <% elsif current_user.candidate? %>
          <li class="nav-item">
            <%= link_to 'Voters', voters_users_path, class:"nav-link"%>
          </li>
        <% elsif current_user.voter? && DateTime.now <= Schedule.first.election_start_time%>
          <li class="nav-item">
            <%= link_to 'New request', new_request_path, class:"nav-link"%>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to 'Election schedule', schedules_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Candidates', candidates_users_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class:"nav-link"%>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign in', new_user_session_path, class:"nav-link"%>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Welcome to Online Voting machine</h1>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= alert %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/_notice.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

   <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>VotingMachine</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "home/header"%>
  <div class = "container">
  <% if alert %>
    <%= render "layouts/alerts"%><br>
  <% elsif notice %>
    <%= render "layouts/notice"%><br>
  <% end %>
      <%= yield %>
  </div>

   <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

  </body>
</html>

app/views/requests/_form.html.erb
<%= form_with(model: request, local: true) do |form| %>
  <div class="field form-group">
    <%= form.text_field :party_name, placeholder: "Party name", required: true, class:"form-control"%>
  </div>
  <div class="field form-group">
    <h4>Party symbol</h4>
    <%= form.file_field :avatar, required: true %>
  </div>
  <div class="actions">
    <%= form.submit%>
  </div>
<% end %>

app/views/requests/index.html.erb
<h1>Requests</h1>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>CNIC</th>
      <th>Constituency name</th>
      <th>Party name</th>
      <th>Symbol</th>
      <th>Request status</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.name %></td>
        <td><%= request.cnic %></td>
        <td><%= request.constituency_name %></td>
        <td><%= request.party_name %></td>
        <td><%= image_tag request.avatar, width: "100px" if request.avatar.attached? %></td>
        <td><%= request.request_status%></td>
        <td>
          <% if request.request_status == 'pending' %>
            <%= button_to "Approve", request ,method: :patch%>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/requests/new.html.erb
<h1>Request for Candidate-ship</h1>
<%= render 'form', request: @request %>

app/views/schedules/_form.html.erb
<%= form_with(model: schedule, local: true) do |form| %>

  <div class="field">
    <%= form.label :election_start_time %>
    <%= form.datetime_field :election_start_time, required: true, class:"form-control", placeholder:"Election_Start_Time" %>
  </div>

  <div class="field">
    <%= form.label :election_end_time %>
    <%= form.datetime_field :election_end_time, required: true, class:"form-control", placeholder:"Election_End_Time" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1>Edit schedule</h1>

<%= render 'form', schedule: @schedule %>

app/views/schedules/index.html.erb
<h1>Schedule</h1>

<table class="table">
  <thead>
    <tr>
      <th>Electione will start at:</th>
      <th>Electione will end at:</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.election_start_time %></td>
        <td><%= schedule.election_end_time %></td>
        <td>
          <% if current_user.admin? || current_user.super_admin? %>
            <% if @schedules.all.exists? %>
              <%= link_to 'Edit this schedule ? ', edit_schedule_path(schedule), class:"btn btn-primary btn-lg" %>
            <% end %>
          <%end%>
        </td>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/users/candidates.html.erb
<h1>Candidates</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>CNIC</th>
      <th>Email</th>
      <th>Constituency</th>
      <th>Party name</th>
      <th>Symbol</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @userlists.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.cnic %></td>
        <td><%= user.email %></td>
        <td><%= user.constituency_name %></td>
        <td><%= user.party_name%>
        <td><%= image_tag user.avatar, width: "100px" if user.avatar.attached?%>
        <td>
          <% if current_user.voted == false && DateTime.now.between?(Schedule.first.election_start_time, Schedule.first.election_end_time)%>


            <%= button_to "Vote",user_path(user),method: :patch%>

          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/index.html.erb
<h1>Users</h1>

<table class="table">
  <thead>
    <tr>
      <th>Profile pic</th>
      <th>Name</th>
      <th>CNIC</th>
      <th>Email</th>
      <th>Constituency</th>
      <th>Type</th
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @userlists.each do |user| %>
      <tr>
        <td><%= image_tag user.image, width: "100px" if user.image.attached?%>
        <td><%= user.name %></td>
        <td><%= user.cnic %></td>
        <td><%= user.email %></td>
        <td><%= user.constituency_name %></td>
        <td><%= user.user_status %></td>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/invitations/edit.html.erb
<h2><%= t "devise.invitations.edit.header" %></h2>

<%= form_for(resource, as: resource_name, url: invitation_path(resource_name), html: { method: :put }) do |f| %>

  <%= f.hidden_field :invitation_token, readonly: true %>

  <% if f.object.class.require_password_on_accepting %>

    <div class="field">
      <h6>Profile image</h6>
      <%= f.file_field :image %>
    </div>

    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password, required: true %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, required: true %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit t("devise.invitations.edit.submit_button") %>
  </div>
<% end %>

app/views/users/invitations/new.html.erb
<h2><%= t "devise.invitations.new.header" %></h2>

<%= form_for(resource, as: resource_name, url: invitation_path(resource_name), html: { method: :post }) do |f| %>

  <% resource.class.invite_key_fields.each do |field| -%>


    <div class="field form-group">
      <%= f.text_field :name, class:'form-control', placeholder:'Voter Name', required: true%>
    </div>

    <div class="field form-group">
      <%= f.email_field :email, class:'form-control', placeholder:'Voter Email', required: true%>
    </div>

    <div class="field form-group">
      <%= f.text_field :cnic, class:'form-control', placeholder:'Voter CNIC', required: true, length: 13%>
    </div>

    <div class="field form-group">
      <%= f.select :constituency_id, options_for_select(Constituency.all.pluck(:id)), {prompt: "Select Constituency ID"}, class:'form-control', placeholder:'Constituency id', required: true%>
    </div>

    <div class="field form-group">
      <%= f.select :constituency_name, options_for_select(Constituency.all.pluck(:name)), {prompt: "Select corresponding constituency name"}, class:'form-control', placeholder:'Constituency Name', required: true %>
    </div>

    <div class="field form-group">
      <%= f.select :user_status, options_for_select(["voter"]), {prompt: "Select Status"}, class:'form-control', placeholder:'Type' %>
    </div>

  <% end -%>


  <div class="actions">
    <%= f.submit t("devise.invitations.new.submit_button"), class: 'btn btn-success' %>
  </div>
<% end %>

app/views/users/voters.html.erb
<h1>Voters</h1>

<table class="table">
  <thead>
    <tr>
      <th>Profile pic</th>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @userlists.each do |user| %>
      <tr>
        <td><%= image_tag user.image, width: "100px" if user.image.attached? %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/voterslists/index.html.erb
<h1>Voters</h1>

<table class="table">
  <thead>
    <tr>
      <th>Profile pic</th>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @userlists.each do |user| %>
      <tr>
        <td><%= image_tag user.image, width: "100px" if user.image.attached? %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>